{{- include "buildkit-cache-controller.validateAllowedNamespaces" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildkit-cache-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "buildkit-cache-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "buildkit-cache-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "buildkit-cache-controller.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "buildkit-cache-controller.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --health-probe-bind-address=:{{ .Values.healthProbe.port }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            - --leader-elect-id={{ include "buildkit-cache-controller.leaderElectionID" . }}
            - --leader-elect-namespace={{ .Release.Namespace }}
            {{- end }}
            - --allowed-namespaces={{ join "," .Values.allowedNamespaces }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            - name: probe
              containerPort: {{ .Values.healthProbe.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
